# Generated by Django 5.1 on 2024-10-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_confidence', models.FloatField(help_text='How confident the AI is about its analysis (0-1)')),
                ('detected_ips', models.JSONField(blank=True, help_text='IP addresses found in the incident description', null=True)),
                ('detected_urls', models.JSONField(blank=True, help_text='URLs found in the incident description', null=True)),
                ('detected_systems', models.JSONField(blank=True, help_text='Usernames or system names found in the description', null=True)),
                ('ai_recommendations', models.JSONField(help_text='AI-generated recommendations for handling the incident')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Incident Analyses',
            },
        ),
        migrations.CreateModel(
            name='RelatedIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='How similar these incidents are (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_relationships', to='incidents.incident')),
                ('related_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_relationships', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Related Incidents',
                'unique_together': {('primary_incident', 'related_incident')},
            },
        ),
    ]
