# Generated by Django 5.1 on 2024-10-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentanalysis_relatedincidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
